stages:
  download_data:
    cmd: PYTHONPATH=. python3 scripts/download_data.py
    deps:
    - scripts/download_data.py
    params:
    - download_data.dev_domains
    - download_data.test_domains
    - download_data.text_cfg
    - download_data.train_domains
    outs:
    - data/dataset.pkl
  extract_features:
    cmd: PYTHONPATH=. python3 scripts/extract_features.py
    deps:
    - data/dataset.pkl
    - scripts/extract_features.py
    outs:
    - data/featurized.pkl
  evaluate_model:
    cmd: PYTHONPATH=. python3 scripts/evaluate_model.py
    deps:
    - data/featurized.pkl
    - scripts/evaluate_model.py
    params:
    - evaluate_model.max_iter
    - evaluate_model.random_state
    metrics:
    - data/results.json:
        cache: false
